type Cat = {
  name: string;
  id: number;
}
export type DataType = Cat;

export const data: Cat[] = [
  { name: 'Gato', id: 1 },
  { name: 'Viktor', id: 2 },
  { name: 'Adam', id: 3 },
  { name: 'Beker', id: 4 },
  { name: 'Uan', id: 5 },
  { name: 'Smokey', id: 6 },
  { name: 'Oreo', id: 7 },
  { name: 'Felix', id: 8 },
  { name: 'Sylvester', id: 9 },
  { name: 'Garfield', id: 10 },
  { name: 'Tom', id: 11 },
  { name: 'Jerry', id: 12 },
  { name: 'Heathcliff', id: 13 },
  { name: 'Simba', id: 14 },
  { name: 'Nala', id: 15 },
  { name: 'Luna', id: 16 },
  { name: 'Bella', id: 17 },
  { name: 'Lucy', id: 18 },
  { name: 'Chloe', id: 19 },
  { name: 'Molly', id: 20 },
  { name: 'Daisy', id: 21 },
  { name: 'Lily', id: 22 },
  { name: 'Cleo', id: 23 },
  { name: 'Sasha', id: 24 },
  { name: 'Angel', id: 25 },
  { name: 'Loki', id: 26 },
  { name: 'Ziggy', id: 27 },
  { name: 'Jasper', id: 28 },
  { name: 'Boots', id: 29 },
  { name: 'Milo', id: 30 },
  { name: 'Max', id: 31 },
  { name: 'Charlie', id: 32 },
  { name: 'Jack', id: 33 },
  { name: 'Oliver', id: 34 },
  { name: 'Buddy', id: 35 },
  { name: 'Leo', id: 36 },
  { name: 'Shadow', id: 37 },
  { name: 'Toby', id: 38 },
  { name: 'Oscar', id: 39 },
  { name: 'Simon', id: 40 },
  { name: 'Sam', id: 41 },
  { name: 'Gizmo', id: 42 },
  { name: 'Bandit', id: 43 },
  { name: 'Rusty', id: 44 },
  { name: 'Pepper', id: 45 },
  { name: 'Misty', id: 46 },
  { name: 'Missy', id: 47 },
  { name: 'Muffin', id: 48 },
  { name: 'Pumpkin', id: 49 },
  { name: 'Cupcake', id: 50 },
];
